sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y maven
  - sudo apt-get install -y chromium-browser
  - sudo apt-get install -y chromium-chromedriver
  - sudo apt-get install -y libxi6
  - sudo apt-get install -y libgconf-2-4
  - sudo apt-get install -y xvfb
  - sudo apt-get install -y x11vnc
  - sudo apt-get install -y imagemagick
  - sudo apt-get install -y x11-apps
  - export DISPLAY=:99
  - XVFB="/usr/bin/Xvfb"
  - XVFB_ARGS="-ac $DISPLAY -screen 0 1280x1024x16"
  - sudo start-stop-daemon --start --quiet --pidfile /var/run/xvfb.pid --make-pidfile --background --exec $XVFB -- $XVFB_ARGS

install: true

script:
  - mvn clean install

after_script:
  - sudo killall Xvfb