sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk8

services:
  - docker

addons:
  hosts:
    - local.example.com
    - local.example.org

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y maven
  - sudo apt-get -qq install -y chromium-browser
  - sudo apt-get -qq install -y chromium-chromedriver
  - sudo apt-get -qq install -y libxi6
  - sudo apt-get -qq install -y libgconf-2-4
  - sudo apt-get -qq install -y openssl
  - sudo apt-get -qq install -y libnss3-tools

before_script:
  - openssl pkcs12 -in SampleApplication/src/main/resources/keystore.p12 -passin pass:my_keystore_password -out /tmp/localhost.pem -passout pass:my_pem_password
  - echo "my_pem_password" > /tmp/pwdfile.txt
  - mkdir -p $HOME/.pki/nssdb
  - certutil -d sql:$HOME/.pki/nssdb -N --empty-password
  - certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localhost -i /tmp/localhost.pem -f /tmp/pwdfile.txt

script:
  - mvn clean install --batch-mode -DchromeDriverBinary=/usr/lib/chromium-browser/chromedriver -DchromeBinary=/usr/bin/chromium-browser -DchromeHeadless=true -DrunNonLocalHostTests=true
  - ./gradlew clean build -DchromeDriverBinary=/usr/lib/chromium-browser/chromedriver -DchromeBinary=/usr/bin/chromium-browser -DchromeHeadless=true -DrunNonLocalHostTests=true